version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3@sha256:9ad2cc2e228dc5f00ac5dcaf3fd83dcedfee4b3a6f779515060070c46891fa10
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: Test coverage
          command: npm run test:coverage
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)
