version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2@sha256:1766b060890be2ca13e031f61d1b49b0f6f5952ba385bd40abe8e6042f6b03bc
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: Test coverage
          command: npm run test:coverage
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)
