version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.2@sha256:635bffb70b37d99eb4935a1e96994ed018da36882f4fadc71b1731f083cf645f
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run unit tests
          command: npm run test:unit
      - run:
          name: Test coverage
          command: npm run test:coverage
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)
